[project]
name = "gendict"
version = "0.0.1"

dependencies = [
    "blablador @ git+https://github.com/Global-Health-Engineering/blablador.git@main#egg=blablador",
    "pandas",
    "regex"
]

[tool.setuptools]
packages = ["gendict"]